#####################################################################################################################
# Title:         Node & NPM Installer                                                                               #
# Author(s):     mario-galindo & Logan                                                                              #
# Reference(s): https://gist.github.com/komuw/b3b5d24977d4df7bd549?permalink_comment_id=3821746#gistcomment-3821746 #
#####################################################################################################################

- name: Setup Node
  become: yes
  become_flags: 
    - -i
  tasks:
    - name: Install nvm
      ansible.builtin.shell: >
        curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.5/install.sh | bash
      args:
        executable: /bin/bash
        chdir: "$HOME"
        creates: "$HOME/.nvm/nvm.sh"

    - name: Setup .profile
      ansible.builtin.lineinfile:
        path: ~/.profile
        line: source ~/.nvm/nvm.sh # This will make sure Node is on the user's PATH
        create: yes

    - name: Install node
      ansible.builtin.shell: |
        nvm install {{item}}
      args:
        executable: /bin/bash
        chdir: "$HOME"
        creates: "$HOME/.nvm/versions/node/v{{item}}"
      loop:
        - 18.18.2
